In [4]:
scores = [11, 22, 33]
new_scores = []

for score in scores:
    new_scores.append(score + 3)

print(new_scores)

[14, 25, 36]


In [5]:
scores = [11, 22, 33]
new_scores = [score+3 for score in scores]
new_scores

[14, 25, 36]

In [11]:
import numpy as np

scores = np.array([11 ,22, 33])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([14, 25, 36])

In [12]:
students = np.array([
    [67, 94, 65],
    [78, 92, 68],
    [59, 92, 87]
    ])
students

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [14]:
students.ndim, students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int32'))

In [18]:
students[0,:]

array([67, 94, 65])

In [19]:
students[0:2,:]

array([[67, 94, 65],
       [78, 92, 68]])

In [23]:
students[-2:,:]+3

array([[81, 95, 71],
       [62, 95, 90]])

In [21]:
students[:,0]

array([67, 78, 59])

In [22]:
students[:,:2]

array([[67, 94],
       [78, 92],
       [59, 92]])

In [24]:
students[0,0]

67

In [26]:
students[0, 0] = 100
students

array([[100,  94,  65],
       [ 78,  92,  68],
       [ 59,  92,  87]])

In [27]:
students[0, 0] -= 10
students

array([[90, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])